### ISSUE TITLE
Using "<<" operator twice

### ISSUE THREAD

**Issue by Awiomanik** [Arian8j2/ClipboardXX#3]
Hey,
at the beginning, I would like to mention that I'm a beginner programmer, that is my first activity on Github and so I ask for leniency.
So I tried to use your library in my program and whenever I copy something for the second time I get a critical error (c0000374) in line 279 (`SetClipboardData(CF_TEXT, global);`). Moreover, there is a warning (C28183).
I think that the clipboard is not "closing/deleting/empty/...." itself and that is why the program cannot rerun the copy function.

- In my program, I added `clipboardxx::clipboard clp;` at the beginning of the main function,

- then used overflown operator `<<` in a switch _(users choice of action)_ in a while _(menu with actions)_ loop (`clp << password;`)

Thank you in advance for your reply.

**Comment by Arian8j2** [comment]
First of all, Thanks for reporting this, I really not tested windows side codes enough and all codes about it are kinda old. The issue was simple, I freed the data after setting the clipboard data but that was unnecessary and even bad thing to do according to [Windows docs](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setclipboarddata):
> The application may not write to or free the data once ownership has been transferred to the system

After all, I reviewed the docs and thought it's better to close clipboard when we are not using it, So basically now when calling **copy** or **paste** function it opens clipboard, do it's job and then closes the clipboard.

d404c39 fixes this issue.
